blog/urls.py
from django.conf.urls import url
from .views import PostCreate,PostDetail,\
    PostUpdate,PostDelete,PostList,CommentCreate,ChildCommentCreate,CommentDelete

urlpatterns=[

    url(r'^comment/(?P<comment_id>[^/]+)/'
        r'delete/$',
        CommentDelete.as_view(),
        name='blog_comment_delete'),
    url(r'^comment/(?P<parent_id>[^/]+)/'
        r'create/$',
        ChildCommentCreate.as_view(),
        name='blog_child_comment_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'comment/create/$',
        CommentCreate.as_view(),
        name='blog_comment_create'),
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        PostDetail.as_view(),
        name='blog_post_detail'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import urls as blog_urls
from django.views.generic import RedirectView,TemplateView
from bloguser import urls as user_urls
from blog.feeds import AtomPostFeed,Rss2PostFeed
from django.contrib.sitemaps.views import (
    index as site_index_view,
    sitemap as sitemap_view)
from .sitemaps import sitemaps as sitemaps_dict


admin.site.site_header='Blog Project Admin'
admin.site.site_title='Blog Project Site Admin'

sitenews=[
    url(r'^atom/$',
        AtomPostFeed(),
        name='blog_atom_feed'),
    url(r'^rss/$',
        Rss2PostFeed(),
        name='blog_rss_feed'),
]

urlpatterns = [
    url(r'^$',RedirectView.as_view(
        pattern_name='blog_post_list',
        permanent=False)),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include(blog_urls)),
    url(r'^user/', include(
        user_urls,
        app_name='bloguser',
        namespace='dj-auth')),
    url(r'^sitenews/',include(sitenews)),
    url(r'^sitemap\.xml$',
        site_index_view,
        {'sitemaps':sitemaps_dict},
        name='sitemap'),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        sitemap_view,
        {'sitemaps':sitemaps_dict},
        name='sitemap-sections'),
]

blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from datetime import date
import uuid


class BasePostManager(models.Manager):
    def get_queryset(self):
        return(
            PostQueryset(
                self.model,
                using=self._db,
                hints=self._hints)
            .select_related('author__profile'))


    def get_by_natural_key(self,pub_date,slug):
        return self.get(
            pub_date=pub_date,
            slug=slug)

class PostQueryset(models.QuerySet):
    def published(self):
        return self.filter(
            pub_date__lte=date.today())

#
# class PostManager(models.Manager):
#     def published(self):
#         return self.get_queryset().filter(
#             pub_date__lte=date.today())

#ConnectedPostManager=PostManager.from_queryset(PostQueryset)

PostManager=BasePostManager.from_queryset(PostQueryset)

class Post(models.Model):
    title=models.CharField(max_length=63)
    slug=models.SlugField(max_length=63,
                          help_text='A label for URL config',
                          unique_for_month='pub_date')
    text=models.TextField()
    pub_date=models.DateField('date_published',
                              auto_now_add=True)
    author=models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='blog_posts')

    objects= PostManager()

    def __str__(self):
        return "{} on {}".format(self.title,
                                 self.pub_date.strftime('%Y-%m-%d'))
    class Meta:
        verbose_name='blog_post'
        ordering=['-pub_date','title']
        get_latest_by='pub_date'
        index_together=('slug','pub_date')

    def get_absolute_url(self):
        return reverse('blog_post_detail',kwargs={
            'year':self.pub_date.year,
            'month':self.pub_date.month,
            'slug':self.slug})

    def get_update_url(self):
        return reverse('blog_post_update',
                       kwargs={
                           'year':self.pub_date.year,
                           'month':self.pub_date.month,
                           'slug':self.slug})
    def get_delete_url(self):
        return reverse('blog_post_delete',
                       kwargs={
                           'year':self.pub_date.year,
                           'month':self.pub_date.month,
                           'slug':self.slug})
    def natural_key(self):
        return (self.pub_date,self.slug)

    natural_key.dependencies=[
        'bloguser.user',
    ]

    def formatted_title(self):
        return self.title.title()

    def short_text(self):
        if len(self.text) > 20:
            short = ' '.join(self.text.split()[:20])
            short+=' ...'
        else:
            short=self.text
        return short

class Comment(models.Model):
    text=models.TextField()
    date_added=models.DateField('date_added',auto_now_add=True)
    #uuid=models.UUIDField(default=uuid.uuid4, editable=False)
    uuid=models.CharField('uuid',max_length=50)
    depth=models.IntegerField('depth',default=0)
    parent=models.ForeignKey("Comment",null=True,blank=True,default=None)

    # slug=models.SlugField(max_length=31,unique=True,
    #                       help_text='A label for URL config')
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='blog_comments')

    def __str__(self):
        return "Comment added on {}".format(
            self.date_added.strftime('%Y-%m-%d'))

    @property
    def depth_multiply(self):
        return self.depth*50

    class Meta:
        verbose_name='comment'
        ordering=['-date_added']
        get_latest_by='date_added'
        permissions=(
            ("view_child_comments",
             "Can view child comments"),
        )

blog/forms.py
from django import forms
from .models import Post,Comment
from django.contrib.auth import get_user


class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        exclude=('author',)

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

    def save(self,request,commit=True):
        post=super().save(commit=False)
        if not post.pk:
            post.author=get_user(request)
        if commit:
            post.save()
            self.save_m2m
        return post

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields='__all__'

blog/views.py
from django.shortcuts import render
from django.shortcuts import (get_object_or_404,render)
from .models import Post,Comment
from django.views.generic import CreateView,ListView,\
    YearArchiveView,View,\
    MonthArchiveView,ArchiveIndexView,\
    DateDetailView,DetailView,DeleteView
from django.views.decorators.http import require_http_methods
from .forms import PostForm,CommentForm
from django.shortcuts import get_object_or_404,render,redirect
from django.core.urlresolvers import reverse,reverse_lazy
from core.utils import UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required
from django.contrib.auth import PermissionDenied
from django.contrib.auth.decorators import user_passes_test
import logging
import uuid
from bloguser.decorators import (
    custom_login_required,
    require_authenticated_permission,
    class_login_required)
from .utils import PostFormValidMixin


logger=logging.getLogger(__name__)

def in_contrib_group(user):
    if user.groups.filter(name='contributors').exists():
        return True
    else:
        raise PermissionDenied

@require_authenticated_permission('blog.add_comment')
class CommentCreate(View):

    def post(self,request,*args,**kwargs):
        comment=Comment()
        comment.text=request.POST['text']
        year=kwargs.get('year')
        month=kwargs.get('month')
        slug=kwargs.get('slug')

        post=Post.objects.filter(pub_date__year=year,pub_date__month=month,slug__iexact=slug)[0]
        comment.post=post
        comment.uuid=uuid.uuid4()
        #comment.parent=None

        comment.save()

        return redirect(
            reverse('blog_post_detail',
                        kwargs={
                            'year':year,
                            'month':month,
                            'slug':slug,
                    }))

@require_authenticated_permission('blog.add_comment')
class ChildCommentCreate(View):
    def post(self,request,*args,**kwargs):
        parent_id=kwargs.get('parent_id')
        text=request.POST['text']

        year=request.POST['year']
        month=request.POST['month']
        slug=request.POST['slug']

        logger.error('year: %s, month:%s, slug=%s' % (year,month,slug))

        parent=Comment.objects.filter(uuid__iexact=parent_id)[0]
        parent_depth=parent.depth

        post=Post.objects.filter(pub_date__year=year,pub_date__month=month,slug__iexact=slug)[0]

        comment=Comment()
        comment.text=text
        comment.depth=parent_depth+1
        comment.uuid=uuid.uuid4()

        comment.parent=parent
        comment.post=post

        comment.save()

        return redirect(
            reverse('blog_post_detail',
                    kwargs={
                        'year':year,
                        'month':month,
                        'slug':slug,
                    }))

@require_authenticated_permission('blog.delete_comment')
class CommentDelete(View):
    def post(self,request,*args,**kwargs):

        year = request.POST['year']
        month = request.POST['month']
        slug = request.POST['slug']

        comment_id=kwargs['comment_id']
        #uuid_str='UUID(\''+uuid.UUID(comment_id).__str__()+'\')'
        logger.error(comment_id)

        comment=Comment.objects.filter(uuid__iexact=comment_id)[0]

        if comment:
            comment.delete()

        return redirect(
            reverse('blog_post_detail',
                       kwargs={
                           'year':year,
                           'month':month,
                           'slug':slug,
                       }))

@require_authenticated_permission('blog.add_post')
class PostCreate(PostFormValidMixin,CreateView):
    form_class = PostForm
    model=Post

@require_authenticated_permission('blog.delete_post')
class PostDelete(DeleteView):
    date_field='pub_date'
    model=Post
    success_url = reverse_lazy('blog_post_list')

class PostDetail(DetailView):
    form_class=CommentForm
    date_field='pub_date'
    model=Post
    queryset = (
        Post.objects
            .select_related('author__profile')
    )


class PostList(ListView):
    template_name='blog/post_list.html'
    model=Post
    paginate_by = 20

    def get(self,request):
        return render(
            request,
            self.template_name,
            {'post_list':Post.objects.all()})


@require_authenticated_permission('blog.change_post')
class PostUpdate(PostFormValidMixin,UpdateView):
    date_field='pub_date'
    form_class=PostForm
    model=Post

blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

{% load staticfiles %}

blog/templates/blog/commentfragment.html
{% for comment in children %}

    <div style="position:relative;left:50px;">
        <p>{{ comment.text }}</p>

        {% if perms.blog.delete_comment %}
        <form action="{% url 'blog_comment_delete' comment.uuid %}" method="post">
                {% csrf_token %}
                <input type="hidden" id="year" name="year" value="{{ post.pub_date.year }}"/>
                <input type="hidden" id="month" name="month" value="{{ post.pub_date.month }}"/>
                <input type="hidden" id=slug" name="slug" value="{{ post.slug }}"/>

                <button class="btn btn-danger" type="submit">Delete</button>
        </form>
        {% endif %}

        <form action="{% url 'blog_child_comment_create' comment.uuid %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="hidden" id="year" name="year" value="{{ post.pub_date.year }}"/>
                <input type="hidden" id="month" name="month" value="{{ post.pub_date.month }}"/>
                <input type="hidden" id=slug" name="slug" value="{{ post.slug }}"/>

                <input id="id_child_text" class="form-control" name="text" type="text"/>
                <button class="btn btn-primary" type="submit">
                    Comment
                </button>
            </div>
        </form>
        {% include 'blog/commentfragment.html' with children=comment.comment_set.all %}
    </div>
{% endfor %}

blog/templates/blog/post_confirm_delete.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
{{ block.super }} - Post Confirm Delete
{% endblock %}

{% block content%}
<div>
    <div>
        <form action="{{ newslink.get_delete_url }}"
              method="post">
            {% csrf_token %}
            <p>
                Are you sure you want to delete post {{ post.slug }}?
            </p>
            <a href="{{ post.get_absolute_url }}" class="button button-primary">
                Cancel
            </a>
            <button type="submit" class="btn btn-danger">Delete Post</button>

        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
{{ block.super }} - Post Detail
{% endblock %}

{% block content %}
<article>
    <div>
        <div>
            <header>
                <h2>{{ post.title|title }}</h2>

                <ul>
                    {% if perms.blog.change_post %}
                    <li>
                        <a href="{{ post.get_update_url }}" class="button button-primary">
                            Edit Post
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.blog.delete_post %}
                    <li>
                        <a href="{{ post.get_delete_url }}" class="button button-primary">
                            Delete Post
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <p>
                    Written on
                    <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                        {{ post.pub_date|date:"l, F j, Y" }}
                    </time>
                    by
                    <a href="{{ post.author.get_absolute_url }}">
                        {{ post.author.profile.name }}
                    </a>
                </p>
            </header>

            {{ post.text|linebreaks }}

            {% if perms.blog.delete_post %}
             <form action="{% url 'blog_post_delete' post.pub_date.year post.pub_date.month post.slug %}" method="post">
                {% csrf_token %}
                 <div class="form-group">
                     <button class="btn btn-danger" type="submit">Delete</button>
                 </div>
             </form>
            {% endif %}

            {% if perms.blog.add_comment %}
            <form action="{% url 'blog_comment_create' post.pub_date.year post.pub_date.month post.slug %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input id="id_text" class="form-control" name="text" type="text"/>
                    <button class="btn btn-primary" type="submit">
                        Comment
                    </button>
                </div>
            </form>
            {% endif %}
        </div>
    </div>


{% if post.comment_set.all %}
    <footer>
        <section>
          {% comment %}  <h3>Comment{{ post.comment_set.count|pluralize }}</h3>{% endcomment %}
                <div class="container">
                    <div class="jumbotron">
                        {% for comment in post.comment_set.all %}
                            {% if comment.depth == 0 %}
                            <p>{{ comment.text }}</p>

                                {% if perms.blog.delete_comment %}
                                <form action="{% url 'blog_comment_delete' comment.uuid %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" id="year" name="year" value="{{ post.pub_date.year }}"/>
                                    <input type="hidden" id="month" name="month" value="{{ post.pub_date.month }}"/>
                                    <input type="hidden" id=slug" name="slug" value="{{ post.slug }}"/>

                                    <button class="btn btn-danger" type="submit">Delete</button>
                                 </form>
                                {% endif %}

                                {% if perms.blog.view_child_comments %}
                                <form action="{% url 'blog_child_comment_create' comment.uuid %}" method="post">
                                {% csrf_token %}
                                    <div class="form-group">
                                        <input type="hidden" id="year" name="year" value="{{ post.pub_date.year }}"/>
                                        <input type="hidden" id="month" name="month" value="{{ post.pub_date.month }}"/>
                                        <input type="hidden" id=slug" name="slug" value="{{ post.slug }}"/>

                                        <input id="id_child_text" class="form-control" name="text" type="text"/>
                                        <button class="btn btn-primary" type="submit">
                                            Comment
                                        </button>
                                    </div>
                                </form>
                            {% include 'blog/commentfragment.html' with children=comment.comment_set.all %}
                            {% endif %}<!--view_child_comments permission
                            {% endif %}<!--comment depth = 0
                        {% endfor %}
                    </div>
                </div>
        </section>
    </footer>
{% endif %}
</article>
{% endblock %}


{#                <li>#}
{#                    {{ comment.text }}#}
{#                    <div>#}
{#                        {% for child in comment.comment_set.all %}#}
{#                            <p>{{ child.text }}</p>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                </li>#}
{#                <li>#}
{#                    <form action="{% url 'blog_child_comment_create' comment.uuid.hex %}" method="post">#}
{#                        {% csrf_token %}#}
{#                        <p>#}
{#                            <input type="hidden" id="year" name="year" value="{{ post.pub_date.year }}"/>#}
{#                            <input type="hidden" id="month" name="month" value="{{ post.pub_date.month }}"/>#}
{#                            <input type="hidden" id=slug" name="slug" value="{{ post.slug }}"/>#}
{##}
{#                            <input id="id_child_text" name="text" type="text"/>#}
{#                        </p>#}
{#                        <button class="btn btn-primary" type="submit">#}
{#                            Comment#}
{#                        </button>#}
{#                    </form>#}
{#                </li>#}

blog/templates/blog/post_form.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% load display_form %}

{% block title %}
{{ block.super }} - Create Blog Post
{% endblock %}

{% block content %}
{#<div>#}
{#    <div>#}
{#        <form action="{% url 'blog_post_create' %}"#}
{#              method="post">#}
{#            {% csrf_token %}#}
{#            {{ form.as_p }}#}
{#            <button class="btn btn-primary" type="submit">#}
{#                Add Post#}
{#            </button>#}
{#        </form>#}
{#    </div>#}
{#</div>#}
{% url 'blog_post_create' as form_url %}
{% form form_url 'Create Blog Post' %}
{% endblock %}

blog/templates/blog/post_form_update.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% load display_form %}

{% block title %}
{{ block.super }} - Update Post
{% endblock %}

{% block content %}
{#<div>#}
{#    <div>#}
{#        <form action="{{ post.get_update_url }}" method="post">#}
{#            {% csrf_token %}#}
{#            {{ form.as_p }}#}
{#            <button class="btn btn-primary" type="submit">#}
{#                Update Post#}
{#            </button>#}
{#        </form>#}
{#    </div>#}
{#</div>#}
{% form post.get_update_url 'Update Blog Post' %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends parent_template|default:"blog/base_blog.html" %}


{% load blog_latest %}

{% block title %}
{{ block.super }} - Blog Posts
{% endblock %}


{% block content %}

    {% get_latest_posts 5 as custom_post_list %}
    <section>
        <h4>Latest Posts</h4>
        <ul>
            {% for latest_post in custom_post_list %}
            <li><a href="{{ latest_post.get_absolute_url }}">
                {{ latest_post.title}}</a></li>
            {% endfor %}
        </ul>
    </section>

{#    {% if messages %}#}
{#    <ul>#}
{#        {% for message in messages %}#}
{#        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#    {% endif %}#}

    {% if perms.blog.add_post %}
    <div>
        <a href="{% url 'blog_post_create' %}">
            Write New Blog Post
        </a>
    </div>
    {% endif %}

    {% for post in post_list %}
    <article>
    <header>
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
            </a>
        </h2>
        <ul class="inline">
            {% if perms.blog.change_post %}
            <li>
                <a href="{{ post.get_update_url }}" class="button">
                    Edit Post
                </a>
            </li>
            {% endif %}
            {% if perms.blog.delete_post %}
            <li>
                <a href="{{ post.get_delete_url }}" class="button">
                    Delete Post
                </a>
            </li>
            {% endif %}
        </ul>

        <p>
           Written on:
            <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                {{ post.pub_date|date:"l, F j, Y" }}
            </time>
            by
            <a href="{{ post.author.get_absolute_url }}">
                {{ post.author.profile.name }}
            </a>
        </p>
    </header>
    <p>{{ post.text|truncatewords:20 }}</p>
    <p>
        <a href="{{ post.get_absolute_url }}">
            Read more&hellip;
        </a>
    </p>
    </article>
    {% empty %}
        <p><em>No Blog Posts Available</em></p>
    {% endfor %}

{% endblock %}